services:
  # text2promql:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./configs:/app/configs
  #     - ./data:/app/data
  #   environment:
  #     - PROMETHEUS_URL=http://prometheus:9090
  #   depends_on:
  #     - prometheus

  prometheus:
    image: prom/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prom_data:/prometheus
    ports:
      - "9090:9090"

  neo4j:
    image: neo4j:5.12.0  # Let's use a stable version instead of 2025.01.0
    restart: unless-stopped
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/txt2promql
      - NEO4J_server_memory_pagecache_size=1G
      - NEO4J_server_memory_heap_initial__size=1G
      - NEO4J_server_memory_heap_max__size=1G
      - NEO4J_ACCEPT_LICENSE_AGREEMENT=yes
      - NEO4J_dbms_connector_bolt_advertised__address=:7687
      - NEO4J_dbms_default__database=neo4j
      - NEO4J_dbms_connector_bolt_listen__address=0.0.0.0:7687
    volumes:
      - ./storage/data:/data
      - ./storage/logs:/logs
      - ./storage/import:/var/lib/neo4j/import
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider localhost:7474 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5