server:
  port: 8082
  timeout: 30s
  max_body_size: 1MB

knowledge_graph:
  schema_path: "./schemas/prometheus.yaml"
  auto_discover: true

semantic_memory:
  enabled: true
  faiss_index: "./data/faiss.index"
  embeddings_model: "sentence-transformers/all-MiniLM-L6-v2"
