server:
  port: 8080
  max_body_size: 2MB

prometheus:
  address: http://localhost:9090
  timeout: 30s

ai:
  model: "gpt-4o-mini"
  api_key: "sk-proj-xxxxxxxxxxxx"
  temperature: 0.7
  top_p: 1.0
  base_url: ""  # Optional: for Azure OpenAI or other endpoints
  proxy_endpoint: ""  # Optional: HTTP/HTTPS proxy
  org_id: ""  # Optional: OpenAI organization ID
  custom_headers: {}  # Optional: Additional headers for API requests

knowledge_graph:
  schema_path: "./configs/prometheus.yaml"
  auto_discover: true

semantic_memory:
  enabled: true
  faiss_index: "./data/faiss.index"
  embeddings_model: "sentence-transformers/all-MiniLM-L6-v2"
