server:
  port: 8083
  max_body_size: 2MB

prometheus:
  address: http://localhost:9090
  timeout: 30s

ai:
  model: "gpt-4o-mini"
  api_key: "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"
  temperature: 0.7
  top_p: 1.0
  base_url: ""  # Optional: for Azure OpenAI or other endpoints
  proxy_endpoint: ""  # Optional: HTTP/HTTPS proxy
  org_id: ""  # Optional: OpenAI organization ID
  custom_headers: {}  # Optional: Additional headers for API requests

knowledge_graph:
  schema_path: "./configs/prometheus.yaml"
  auto_discover: true
  enabled: true 
  graph_database: "neo4j"
  graph_uri: "bolt://localhost:7687"
  graph_user: "neo4j"
  graph_password: "txt2promql"

semantic_memory:
  enabled: true
  faiss_index: "./data/faiss.index"
  embeddings_model: "sentence-transformers/all-MiniLM-L6-v2"
