server:
  port: 8080
  max_body_size: 2MB

prometheus:
  address: http://localhost:9090
  timeout: 30s

# ai:
#   model: gpt-4o-mini
#   temperature: 0.3

knowledge_graph:
  schema_path: "./schemas/prometheus.yaml"
  auto_discover: true

semantic_memory:
  enabled: true
  faiss_index: "./data/faiss.index"
  embeddings_model: "sentence-transformers/all-MiniLM-L6-v2"
